#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMAutomatedReports
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PRO")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_automatedreports_test(tbl_automatedreports_test instance);
    partial void Updatetbl_automatedreports_test(tbl_automatedreports_test instance);
    partial void Deletetbl_automatedreports_test(tbl_automatedreports_test instance);
    partial void Inserttbl_customportfolioreport(tbl_customportfolioreport instance);
    partial void Updatetbl_customportfolioreport(tbl_customportfolioreport instance);
    partial void Deletetbl_customportfolioreport(tbl_customportfolioreport instance);
    partial void Inserttbl_Reportstatus(tbl_Reportstatus instance);
    partial void Updatetbl_Reportstatus(tbl_Reportstatus instance);
    partial void Deletetbl_Reportstatus(tbl_Reportstatus instance);
    partial void Inserttbl_Portfoilolink(tbl_Portfoilolink instance);
    partial void Updatetbl_Portfoilolink(tbl_Portfoilolink instance);
    partial void Deletetbl_Portfoilolink(tbl_Portfoilolink instance);
    partial void Inserttbl_PortfolioReport(tbl_PortfolioReport instance);
    partial void Updatetbl_PortfolioReport(tbl_PortfolioReport instance);
    partial void Deletetbl_PortfolioReport(tbl_PortfolioReport instance);
    partial void Inserttbl_reportfrequency(tbl_reportfrequency instance);
    partial void Updatetbl_reportfrequency(tbl_reportfrequency instance);
    partial void Deletetbl_reportfrequency(tbl_reportfrequency instance);
    partial void Inserttbl_report(tbl_report instance);
    partial void Updatetbl_report(tbl_report instance);
    partial void Deletetbl_report(tbl_report instance);
    partial void Inserttbl_automatedreport(tbl_automatedreport instance);
    partial void Updatetbl_automatedreport(tbl_automatedreport instance);
    partial void Deletetbl_automatedreport(tbl_automatedreport instance);
    partial void Inserttbl_ReportTotal(tbl_ReportTotal instance);
    partial void Updatetbl_ReportTotal(tbl_ReportTotal instance);
    partial void Deletetbl_ReportTotal(tbl_ReportTotal instance);
    partial void Inserttbl_KPI(tbl_KPI instance);
    partial void Updatetbl_KPI(tbl_KPI instance);
    partial void Deletetbl_KPI(tbl_KPI instance);
    partial void Inserttbl_usersite(tbl_usersite instance);
    partial void Updatetbl_usersite(tbl_usersite instance);
    partial void Deletetbl_usersite(tbl_usersite instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::TEMAutomatedReports.Properties.Settings.Default.PROConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_automatedreports_test> tbl_automatedreports_tests
		{
			get
			{
				return this.GetTable<tbl_automatedreports_test>();
			}
		}
		
		public System.Data.Linq.Table<tbl_customportfolioreport> tbl_customportfolioreports
		{
			get
			{
				return this.GetTable<tbl_customportfolioreport>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Reportstatus> tbl_Reportstatus
		{
			get
			{
				return this.GetTable<tbl_Reportstatus>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Portfoilolink> tbl_Portfoilolinks
		{
			get
			{
				return this.GetTable<tbl_Portfoilolink>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortfolioReport> tbl_PortfolioReports
		{
			get
			{
				return this.GetTable<tbl_PortfolioReport>();
			}
		}
		
		public System.Data.Linq.Table<tbl_reportfrequency> tbl_reportfrequencies
		{
			get
			{
				return this.GetTable<tbl_reportfrequency>();
			}
		}
		
		public System.Data.Linq.Table<tbl_report> tbl_reports
		{
			get
			{
				return this.GetTable<tbl_report>();
			}
		}
		
		public System.Data.Linq.Table<tbl_automatedreport> tbl_automatedreports
		{
			get
			{
				return this.GetTable<tbl_automatedreport>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ReportTotal> tbl_ReportTotals
		{
			get
			{
				return this.GetTable<tbl_ReportTotal>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KPI> tbl_KPIs
		{
			get
			{
				return this.GetTable<tbl_KPI>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usersite> tbl_usersites
		{
			get
			{
				return this.GetTable<tbl_usersite>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_automatedreports_test")]
	public partial class tbl_automatedreports_test : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _schedule_id_PK;
		
		private string _schedule_storedprocedure;
		
		private string _schedule_reportname;
		
		private string _schedule_schedulename;
		
		private string _schedule_reporttype;
		
		private System.DateTime _schedule_createddate;
		
		private string _schedule_filters;
		
		private string _schedule_chosendropdown;
		
		private string _schedule_chosenNodeIds;
		
		private string _schedule_frequency;
		
		private string _schedule_reportformat;
		
		private string _schedule_emailaddresses;
		
		private System.Nullable<int> _schedule_user_id_FK;
		
		private System.Nullable<bool> _schedule_Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onschedule_id_PKChanging(int value);
    partial void Onschedule_id_PKChanged();
    partial void Onschedule_storedprocedureChanging(string value);
    partial void Onschedule_storedprocedureChanged();
    partial void Onschedule_reportnameChanging(string value);
    partial void Onschedule_reportnameChanged();
    partial void Onschedule_schedulenameChanging(string value);
    partial void Onschedule_schedulenameChanged();
    partial void Onschedule_reporttypeChanging(string value);
    partial void Onschedule_reporttypeChanged();
    partial void Onschedule_createddateChanging(System.DateTime value);
    partial void Onschedule_createddateChanged();
    partial void Onschedule_filtersChanging(string value);
    partial void Onschedule_filtersChanged();
    partial void Onschedule_chosendropdownChanging(string value);
    partial void Onschedule_chosendropdownChanged();
    partial void Onschedule_chosenNodeIdsChanging(string value);
    partial void Onschedule_chosenNodeIdsChanged();
    partial void Onschedule_frequencyChanging(string value);
    partial void Onschedule_frequencyChanged();
    partial void Onschedule_reportformatChanging(string value);
    partial void Onschedule_reportformatChanged();
    partial void Onschedule_emailaddressesChanging(string value);
    partial void Onschedule_emailaddressesChanged();
    partial void Onschedule_user_id_FKChanging(System.Nullable<int> value);
    partial void Onschedule_user_id_FKChanged();
    partial void Onschedule_ActiveChanging(System.Nullable<bool> value);
    partial void Onschedule_ActiveChanged();
    #endregion
		
		public tbl_automatedreports_test()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_id_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int schedule_id_PK
		{
			get
			{
				return this._schedule_id_PK;
			}
			set
			{
				if ((this._schedule_id_PK != value))
				{
					this.Onschedule_id_PKChanging(value);
					this.SendPropertyChanging();
					this._schedule_id_PK = value;
					this.SendPropertyChanged("schedule_id_PK");
					this.Onschedule_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_storedprocedure", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string schedule_storedprocedure
		{
			get
			{
				return this._schedule_storedprocedure;
			}
			set
			{
				if ((this._schedule_storedprocedure != value))
				{
					this.Onschedule_storedprocedureChanging(value);
					this.SendPropertyChanging();
					this._schedule_storedprocedure = value;
					this.SendPropertyChanged("schedule_storedprocedure");
					this.Onschedule_storedprocedureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_reportname", DbType="VarChar(50)")]
		public string schedule_reportname
		{
			get
			{
				return this._schedule_reportname;
			}
			set
			{
				if ((this._schedule_reportname != value))
				{
					this.Onschedule_reportnameChanging(value);
					this.SendPropertyChanging();
					this._schedule_reportname = value;
					this.SendPropertyChanged("schedule_reportname");
					this.Onschedule_reportnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_schedulename", DbType="VarChar(50)")]
		public string schedule_schedulename
		{
			get
			{
				return this._schedule_schedulename;
			}
			set
			{
				if ((this._schedule_schedulename != value))
				{
					this.Onschedule_schedulenameChanging(value);
					this.SendPropertyChanging();
					this._schedule_schedulename = value;
					this.SendPropertyChanged("schedule_schedulename");
					this.Onschedule_schedulenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_reporttype", DbType="VarChar(8)")]
		public string schedule_reporttype
		{
			get
			{
				return this._schedule_reporttype;
			}
			set
			{
				if ((this._schedule_reporttype != value))
				{
					this.Onschedule_reporttypeChanging(value);
					this.SendPropertyChanging();
					this._schedule_reporttype = value;
					this.SendPropertyChanged("schedule_reporttype");
					this.Onschedule_reporttypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_createddate", DbType="DateTime NOT NULL")]
		public System.DateTime schedule_createddate
		{
			get
			{
				return this._schedule_createddate;
			}
			set
			{
				if ((this._schedule_createddate != value))
				{
					this.Onschedule_createddateChanging(value);
					this.SendPropertyChanging();
					this._schedule_createddate = value;
					this.SendPropertyChanged("schedule_createddate");
					this.Onschedule_createddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_filters", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string schedule_filters
		{
			get
			{
				return this._schedule_filters;
			}
			set
			{
				if ((this._schedule_filters != value))
				{
					this.Onschedule_filtersChanging(value);
					this.SendPropertyChanging();
					this._schedule_filters = value;
					this.SendPropertyChanged("schedule_filters");
					this.Onschedule_filtersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_chosendropdown", DbType="VarChar(6)")]
		public string schedule_chosendropdown
		{
			get
			{
				return this._schedule_chosendropdown;
			}
			set
			{
				if ((this._schedule_chosendropdown != value))
				{
					this.Onschedule_chosendropdownChanging(value);
					this.SendPropertyChanging();
					this._schedule_chosendropdown = value;
					this.SendPropertyChanged("schedule_chosendropdown");
					this.Onschedule_chosendropdownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_chosenNodeIds", DbType="VarChar(MAX)")]
		public string schedule_chosenNodeIds
		{
			get
			{
				return this._schedule_chosenNodeIds;
			}
			set
			{
				if ((this._schedule_chosenNodeIds != value))
				{
					this.Onschedule_chosenNodeIdsChanging(value);
					this.SendPropertyChanging();
					this._schedule_chosenNodeIds = value;
					this.SendPropertyChanged("schedule_chosenNodeIds");
					this.Onschedule_chosenNodeIdsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_frequency", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string schedule_frequency
		{
			get
			{
				return this._schedule_frequency;
			}
			set
			{
				if ((this._schedule_frequency != value))
				{
					this.Onschedule_frequencyChanging(value);
					this.SendPropertyChanging();
					this._schedule_frequency = value;
					this.SendPropertyChanged("schedule_frequency");
					this.Onschedule_frequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_reportformat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string schedule_reportformat
		{
			get
			{
				return this._schedule_reportformat;
			}
			set
			{
				if ((this._schedule_reportformat != value))
				{
					this.Onschedule_reportformatChanging(value);
					this.SendPropertyChanging();
					this._schedule_reportformat = value;
					this.SendPropertyChanged("schedule_reportformat");
					this.Onschedule_reportformatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_emailaddresses", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string schedule_emailaddresses
		{
			get
			{
				return this._schedule_emailaddresses;
			}
			set
			{
				if ((this._schedule_emailaddresses != value))
				{
					this.Onschedule_emailaddressesChanging(value);
					this.SendPropertyChanging();
					this._schedule_emailaddresses = value;
					this.SendPropertyChanged("schedule_emailaddresses");
					this.Onschedule_emailaddressesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_user_id_FK", DbType="Int")]
		public System.Nullable<int> schedule_user_id_FK
		{
			get
			{
				return this._schedule_user_id_FK;
			}
			set
			{
				if ((this._schedule_user_id_FK != value))
				{
					this.Onschedule_user_id_FKChanging(value);
					this.SendPropertyChanging();
					this._schedule_user_id_FK = value;
					this.SendPropertyChanged("schedule_user_id_FK");
					this.Onschedule_user_id_FKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_Active", DbType="Bit")]
		public System.Nullable<bool> schedule_Active
		{
			get
			{
				return this._schedule_Active;
			}
			set
			{
				if ((this._schedule_Active != value))
				{
					this.Onschedule_ActiveChanging(value);
					this.SendPropertyChanging();
					this._schedule_Active = value;
					this.SendPropertyChanged("schedule_Active");
					this.Onschedule_ActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_customportfolioreports")]
	public partial class tbl_customportfolioreport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Customportfolio_ID;
		
		private int _schedule_id_PK;
		
		private string _Customportfolio_Report;
		
		private int _Customportfolio_Link;
		
		private System.Nullable<bool> _Customportfolio_Run;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomportfolio_IDChanging(int value);
    partial void OnCustomportfolio_IDChanged();
    partial void Onschedule_id_PKChanging(int value);
    partial void Onschedule_id_PKChanged();
    partial void OnCustomportfolio_ReportChanging(string value);
    partial void OnCustomportfolio_ReportChanged();
    partial void OnCustomportfolio_LinkChanging(int value);
    partial void OnCustomportfolio_LinkChanged();
    partial void OnCustomportfolio_RunChanging(System.Nullable<bool> value);
    partial void OnCustomportfolio_RunChanged();
    #endregion
		
		public tbl_customportfolioreport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customportfolio_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Customportfolio_ID
		{
			get
			{
				return this._Customportfolio_ID;
			}
			set
			{
				if ((this._Customportfolio_ID != value))
				{
					this.OnCustomportfolio_IDChanging(value);
					this.SendPropertyChanging();
					this._Customportfolio_ID = value;
					this.SendPropertyChanged("Customportfolio_ID");
					this.OnCustomportfolio_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_id_PK", DbType="Int NOT NULL")]
		public int schedule_id_PK
		{
			get
			{
				return this._schedule_id_PK;
			}
			set
			{
				if ((this._schedule_id_PK != value))
				{
					this.Onschedule_id_PKChanging(value);
					this.SendPropertyChanging();
					this._schedule_id_PK = value;
					this.SendPropertyChanged("schedule_id_PK");
					this.Onschedule_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customportfolio_Report", DbType="VarChar(500)")]
		public string Customportfolio_Report
		{
			get
			{
				return this._Customportfolio_Report;
			}
			set
			{
				if ((this._Customportfolio_Report != value))
				{
					this.OnCustomportfolio_ReportChanging(value);
					this.SendPropertyChanging();
					this._Customportfolio_Report = value;
					this.SendPropertyChanged("Customportfolio_Report");
					this.OnCustomportfolio_ReportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customportfolio_Link", DbType="Int NOT NULL")]
		public int Customportfolio_Link
		{
			get
			{
				return this._Customportfolio_Link;
			}
			set
			{
				if ((this._Customportfolio_Link != value))
				{
					this.OnCustomportfolio_LinkChanging(value);
					this.SendPropertyChanging();
					this._Customportfolio_Link = value;
					this.SendPropertyChanged("Customportfolio_Link");
					this.OnCustomportfolio_LinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customportfolio_Run", DbType="Bit")]
		public System.Nullable<bool> Customportfolio_Run
		{
			get
			{
				return this._Customportfolio_Run;
			}
			set
			{
				if ((this._Customportfolio_Run != value))
				{
					this.OnCustomportfolio_RunChanging(value);
					this.SendPropertyChanging();
					this._Customportfolio_Run = value;
					this.SendPropertyChanged("Customportfolio_Run");
					this.OnCustomportfolio_RunChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Reportstatus")]
	public partial class tbl_Reportstatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Reportstatus_id;
		
		private int _schedule_id_PK;
		
		private string _Reportstatus_Status;
		
		private System.DateTime _Reportstatus_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReportstatus_idChanging(int value);
    partial void OnReportstatus_idChanged();
    partial void Onschedule_id_PKChanging(int value);
    partial void Onschedule_id_PKChanged();
    partial void OnReportstatus_StatusChanging(string value);
    partial void OnReportstatus_StatusChanged();
    partial void OnReportstatus_DateChanging(System.DateTime value);
    partial void OnReportstatus_DateChanged();
    #endregion
		
		public tbl_Reportstatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reportstatus_id", IsDbGenerated= true, DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Reportstatus_id
		{
			get
			{
				return this._Reportstatus_id;
			}
			set
			{
				if ((this._Reportstatus_id != value))
				{
					this.OnReportstatus_idChanging(value);
					this.SendPropertyChanging();
					this._Reportstatus_id = value;
					this.SendPropertyChanged("Reportstatus_id");
					this.OnReportstatus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_id_PK", DbType="Int NOT NULL")]
		public int schedule_id_PK
		{
			get
			{
				return this._schedule_id_PK;
			}
			set
			{
				if ((this._schedule_id_PK != value))
				{
					this.Onschedule_id_PKChanging(value);
					this.SendPropertyChanging();
					this._schedule_id_PK = value;
					this.SendPropertyChanged("schedule_id_PK");
					this.Onschedule_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reportstatus_Status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Reportstatus_Status
		{
			get
			{
				return this._Reportstatus_Status;
			}
			set
			{
				if ((this._Reportstatus_Status != value))
				{
					this.OnReportstatus_StatusChanging(value);
					this.SendPropertyChanging();
					this._Reportstatus_Status = value;
					this.SendPropertyChanged("Reportstatus_Status");
					this.OnReportstatus_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reportstatus_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Reportstatus_Date
		{
			get
			{
				return this._Reportstatus_Date;
			}
			set
			{
				if ((this._Reportstatus_Date != value))
				{
					this.OnReportstatus_DateChanging(value);
					this.SendPropertyChanging();
					this._Reportstatus_Date = value;
					this.SendPropertyChanged("Reportstatus_Date");
					this.OnReportstatus_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Portfoilolink")]
	public partial class tbl_Portfoilolink : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Protfolio_ID;
		
		private string _Protfolio_report_id;
		
		private string _Protfolio_Name;
		
		private EntitySet<tbl_PortfolioReport> _tbl_PortfolioReports;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProtfolio_IDChanging(int value);
    partial void OnProtfolio_IDChanged();
    partial void OnProtfolio_report_idChanging(string value);
    partial void OnProtfolio_report_idChanged();
    partial void OnProtfolio_NameChanging(string value);
    partial void OnProtfolio_NameChanged();
    #endregion
		
		public tbl_Portfoilolink()
		{
			this._tbl_PortfolioReports = new EntitySet<tbl_PortfolioReport>(new Action<tbl_PortfolioReport>(this.attach_tbl_PortfolioReports), new Action<tbl_PortfolioReport>(this.detach_tbl_PortfolioReports));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protfolio_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Protfolio_ID
		{
			get
			{
				return this._Protfolio_ID;
			}
			set
			{
				if ((this._Protfolio_ID != value))
				{
					this.OnProtfolio_IDChanging(value);
					this.SendPropertyChanging();
					this._Protfolio_ID = value;
					this.SendPropertyChanged("Protfolio_ID");
					this.OnProtfolio_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protfolio_report_id", DbType="VarChar(100)")]
		public string Protfolio_report_id
		{
			get
			{
				return this._Protfolio_report_id;
			}
			set
			{
				if ((this._Protfolio_report_id != value))
				{
					this.OnProtfolio_report_idChanging(value);
					this.SendPropertyChanging();
					this._Protfolio_report_id = value;
					this.SendPropertyChanged("Protfolio_report_id");
					this.OnProtfolio_report_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protfolio_Name", DbType="VarChar(50)")]
		public string Protfolio_Name
		{
			get
			{
				return this._Protfolio_Name;
			}
			set
			{
				if ((this._Protfolio_Name != value))
				{
					this.OnProtfolio_NameChanging(value);
					this.SendPropertyChanging();
					this._Protfolio_Name = value;
					this.SendPropertyChanged("Protfolio_Name");
					this.OnProtfolio_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Portfoilolink_tbl_PortfolioReport", Storage="_tbl_PortfolioReports", ThisKey="Protfolio_ID", OtherKey="Protfolio_ID")]
		public EntitySet<tbl_PortfolioReport> tbl_PortfolioReports
		{
			get
			{
				return this._tbl_PortfolioReports;
			}
			set
			{
				this._tbl_PortfolioReports.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PortfolioReports(tbl_PortfolioReport entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Portfoilolink = this;
		}
		
		private void detach_tbl_PortfolioReports(tbl_PortfolioReport entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Portfoilolink = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortfolioReport")]
	public partial class tbl_PortfolioReport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PortfolioReport_ID;
		
		private string _PortfolioReport_ReportName;
		
		private string _PortfolioReport_Email;
		
		private System.Nullable<int> _Protfolio_ID;
		
		private System.Nullable<int> _schedule_id_PK;
		
		private System.Nullable<bool> _PortfolioReport_Status;
		
		private EntityRef<tbl_Portfoilolink> _tbl_Portfoilolink;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPortfolioReport_IDChanging(int value);
    partial void OnPortfolioReport_IDChanged();
    partial void OnPortfolioReport_ReportNameChanging(string value);
    partial void OnPortfolioReport_ReportNameChanged();
    partial void OnPortfolioReport_EmailChanging(string value);
    partial void OnPortfolioReport_EmailChanged();
    partial void OnProtfolio_IDChanging(System.Nullable<int> value);
    partial void OnProtfolio_IDChanged();
    partial void Onschedule_id_PKChanging(System.Nullable<int> value);
    partial void Onschedule_id_PKChanged();
    partial void OnPortfolioReport_StatusChanging(System.Nullable<bool> value);
    partial void OnPortfolioReport_StatusChanged();
    #endregion
		
		public tbl_PortfolioReport()
		{
			this._tbl_Portfoilolink = default(EntityRef<tbl_Portfoilolink>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortfolioReport_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PortfolioReport_ID
		{
			get
			{
				return this._PortfolioReport_ID;
			}
			set
			{
				if ((this._PortfolioReport_ID != value))
				{
					this.OnPortfolioReport_IDChanging(value);
					this.SendPropertyChanging();
					this._PortfolioReport_ID = value;
					this.SendPropertyChanged("PortfolioReport_ID");
					this.OnPortfolioReport_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortfolioReport_ReportName", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string PortfolioReport_ReportName
		{
			get
			{
				return this._PortfolioReport_ReportName;
			}
			set
			{
				if ((this._PortfolioReport_ReportName != value))
				{
					this.OnPortfolioReport_ReportNameChanging(value);
					this.SendPropertyChanging();
					this._PortfolioReport_ReportName = value;
					this.SendPropertyChanged("PortfolioReport_ReportName");
					this.OnPortfolioReport_ReportNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortfolioReport_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PortfolioReport_Email
		{
			get
			{
				return this._PortfolioReport_Email;
			}
			set
			{
				if ((this._PortfolioReport_Email != value))
				{
					this.OnPortfolioReport_EmailChanging(value);
					this.SendPropertyChanging();
					this._PortfolioReport_Email = value;
					this.SendPropertyChanged("PortfolioReport_Email");
					this.OnPortfolioReport_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protfolio_ID", DbType="Int")]
		public System.Nullable<int> Protfolio_ID
		{
			get
			{
				return this._Protfolio_ID;
			}
			set
			{
				if ((this._Protfolio_ID != value))
				{
					if (this._tbl_Portfoilolink.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProtfolio_IDChanging(value);
					this.SendPropertyChanging();
					this._Protfolio_ID = value;
					this.SendPropertyChanged("Protfolio_ID");
					this.OnProtfolio_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_id_PK", DbType="Int")]
		public System.Nullable<int> schedule_id_PK
		{
			get
			{
				return this._schedule_id_PK;
			}
			set
			{
				if ((this._schedule_id_PK != value))
				{
					this.Onschedule_id_PKChanging(value);
					this.SendPropertyChanging();
					this._schedule_id_PK = value;
					this.SendPropertyChanged("schedule_id_PK");
					this.Onschedule_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortfolioReport_Status", DbType="Bit")]
		public System.Nullable<bool> PortfolioReport_Status
		{
			get
			{
				return this._PortfolioReport_Status;
			}
			set
			{
				if ((this._PortfolioReport_Status != value))
				{
					this.OnPortfolioReport_StatusChanging(value);
					this.SendPropertyChanging();
					this._PortfolioReport_Status = value;
					this.SendPropertyChanged("PortfolioReport_Status");
					this.OnPortfolioReport_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Portfoilolink_tbl_PortfolioReport", Storage="_tbl_Portfoilolink", ThisKey="Protfolio_ID", OtherKey="Protfolio_ID", IsForeignKey=true)]
		public tbl_Portfoilolink tbl_Portfoilolink
		{
			get
			{
				return this._tbl_Portfoilolink.Entity;
			}
			set
			{
				tbl_Portfoilolink previousValue = this._tbl_Portfoilolink.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Portfoilolink.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Portfoilolink.Entity = null;
						previousValue.tbl_PortfolioReports.Remove(this);
					}
					this._tbl_Portfoilolink.Entity = value;
					if ((value != null))
					{
						value.tbl_PortfolioReports.Add(this);
						this._Protfolio_ID = value.Protfolio_ID;
					}
					else
					{
						this._Protfolio_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Portfoilolink");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_reportfrequency")]
	public partial class tbl_reportfrequency : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Frequency_id;
		
		private string _Frequency_Name;
		
		private System.Nullable<int> _Frequency_Time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFrequency_idChanging(int value);
    partial void OnFrequency_idChanged();
    partial void OnFrequency_NameChanging(string value);
    partial void OnFrequency_NameChanged();
    partial void OnFrequency_TimeChanging(System.Nullable<int> value);
    partial void OnFrequency_TimeChanged();
    #endregion
		
		public tbl_reportfrequency()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Frequency_id
		{
			get
			{
				return this._Frequency_id;
			}
			set
			{
				if ((this._Frequency_id != value))
				{
					this.OnFrequency_idChanging(value);
					this.SendPropertyChanging();
					this._Frequency_id = value;
					this.SendPropertyChanged("Frequency_id");
					this.OnFrequency_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Frequency_Name
		{
			get
			{
				return this._Frequency_Name;
			}
			set
			{
				if ((this._Frequency_Name != value))
				{
					this.OnFrequency_NameChanging(value);
					this.SendPropertyChanging();
					this._Frequency_Name = value;
					this.SendPropertyChanged("Frequency_Name");
					this.OnFrequency_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frequency_Time", DbType="Int")]
		public System.Nullable<int> Frequency_Time
		{
			get
			{
				return this._Frequency_Time;
			}
			set
			{
				if ((this._Frequency_Time != value))
				{
					this.OnFrequency_TimeChanging(value);
					this.SendPropertyChanging();
					this._Frequency_Time = value;
					this.SendPropertyChanged("Frequency_Time");
					this.OnFrequency_TimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_reports")]
	public partial class tbl_report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _reports_id_PK;
		
		private string _reports_storedprocedure;
		
		private string _reports_columns;
		
		private string _reports_URL;
		
		private string _reports_graphbindings;
		
		private string _reports_totals;
		
		private string _reports_columntotal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreports_id_PKChanging(int value);
    partial void Onreports_id_PKChanged();
    partial void Onreports_storedprocedureChanging(string value);
    partial void Onreports_storedprocedureChanged();
    partial void Onreports_columnsChanging(string value);
    partial void Onreports_columnsChanged();
    partial void Onreports_URLChanging(string value);
    partial void Onreports_URLChanged();
    partial void Onreports_graphbindingsChanging(string value);
    partial void Onreports_graphbindingsChanged();
    partial void Onreports_totalsChanging(string value);
    partial void Onreports_totalsChanged();
    partial void Onreports_columntotalChanging(string value);
    partial void Onreports_columntotalChanged();
    #endregion
		
		public tbl_report()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reports_id_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int reports_id_PK
		{
			get
			{
				return this._reports_id_PK;
			}
			set
			{
				if ((this._reports_id_PK != value))
				{
					this.Onreports_id_PKChanging(value);
					this.SendPropertyChanging();
					this._reports_id_PK = value;
					this.SendPropertyChanged("reports_id_PK");
					this.Onreports_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reports_storedprocedure", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string reports_storedprocedure
		{
			get
			{
				return this._reports_storedprocedure;
			}
			set
			{
				if ((this._reports_storedprocedure != value))
				{
					this.Onreports_storedprocedureChanging(value);
					this.SendPropertyChanging();
					this._reports_storedprocedure = value;
					this.SendPropertyChanged("reports_storedprocedure");
					this.Onreports_storedprocedureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reports_columns", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string reports_columns
		{
			get
			{
				return this._reports_columns;
			}
			set
			{
				if ((this._reports_columns != value))
				{
					this.Onreports_columnsChanging(value);
					this.SendPropertyChanging();
					this._reports_columns = value;
					this.SendPropertyChanged("reports_columns");
					this.Onreports_columnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reports_URL", DbType="VarChar(100)")]
		public string reports_URL
		{
			get
			{
				return this._reports_URL;
			}
			set
			{
				if ((this._reports_URL != value))
				{
					this.Onreports_URLChanging(value);
					this.SendPropertyChanging();
					this._reports_URL = value;
					this.SendPropertyChanged("reports_URL");
					this.Onreports_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reports_graphbindings", DbType="VarChar(1000)")]
		public string reports_graphbindings
		{
			get
			{
				return this._reports_graphbindings;
			}
			set
			{
				if ((this._reports_graphbindings != value))
				{
					this.Onreports_graphbindingsChanging(value);
					this.SendPropertyChanging();
					this._reports_graphbindings = value;
					this.SendPropertyChanged("reports_graphbindings");
					this.Onreports_graphbindingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reports_totals", DbType="VarChar(550)")]
		public string reports_totals
		{
			get
			{
				return this._reports_totals;
			}
			set
			{
				if ((this._reports_totals != value))
				{
					this.Onreports_totalsChanging(value);
					this.SendPropertyChanging();
					this._reports_totals = value;
					this.SendPropertyChanged("reports_totals");
					this.Onreports_totalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reports_columntotal", DbType="VarChar(2000)")]
		public string reports_columntotal
		{
			get
			{
				return this._reports_columntotal;
			}
			set
			{
				if ((this._reports_columntotal != value))
				{
					this.Onreports_columntotalChanging(value);
					this.SendPropertyChanging();
					this._reports_columntotal = value;
					this.SendPropertyChanged("reports_columntotal");
					this.Onreports_columntotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_automatedreports")]
	public partial class tbl_automatedreport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _schedule_id_PK;
		
		private string _schedule_storedprocedure;
		
		private string _schedule_reportname;
		
		private string _schedule_schedulename;
		
		private string _schedule_reporttype;
		
		private System.DateTime _schedule_createddate;
		
		private string _schedule_filters;
		
		private string _schedule_chosendropdown;
		
		private string _schedule_chosenNodeIds;
		
		private string _schedule_frequency;
		
		private string _schedule_reportformat;
		
		private string _schedule_emailaddresses;
		
		private System.Nullable<int> _schedule_user_id_FK;
		
		private System.Nullable<bool> _schedule_Active;
		
		private System.Nullable<int> _Protfolio_ID;
		
		private System.Nullable<int> _schedule_Time;
		
		private string _schedule_Graph;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onschedule_id_PKChanging(int value);
    partial void Onschedule_id_PKChanged();
    partial void Onschedule_storedprocedureChanging(string value);
    partial void Onschedule_storedprocedureChanged();
    partial void Onschedule_reportnameChanging(string value);
    partial void Onschedule_reportnameChanged();
    partial void Onschedule_schedulenameChanging(string value);
    partial void Onschedule_schedulenameChanged();
    partial void Onschedule_reporttypeChanging(string value);
    partial void Onschedule_reporttypeChanged();
    partial void Onschedule_createddateChanging(System.DateTime value);
    partial void Onschedule_createddateChanged();
    partial void Onschedule_filtersChanging(string value);
    partial void Onschedule_filtersChanged();
    partial void Onschedule_chosendropdownChanging(string value);
    partial void Onschedule_chosendropdownChanged();
    partial void Onschedule_chosenNodeIdsChanging(string value);
    partial void Onschedule_chosenNodeIdsChanged();
    partial void Onschedule_frequencyChanging(string value);
    partial void Onschedule_frequencyChanged();
    partial void Onschedule_reportformatChanging(string value);
    partial void Onschedule_reportformatChanged();
    partial void Onschedule_emailaddressesChanging(string value);
    partial void Onschedule_emailaddressesChanged();
    partial void Onschedule_user_id_FKChanging(System.Nullable<int> value);
    partial void Onschedule_user_id_FKChanged();
    partial void Onschedule_ActiveChanging(System.Nullable<bool> value);
    partial void Onschedule_ActiveChanged();
    partial void OnProtfolio_IDChanging(System.Nullable<int> value);
    partial void OnProtfolio_IDChanged();
    partial void Onschedule_TimeChanging(System.Nullable<int> value);
    partial void Onschedule_TimeChanged();
    partial void Onschedule_GraphChanging(string value);
    partial void Onschedule_GraphChanged();
    #endregion
		
		public tbl_automatedreport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_id_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int schedule_id_PK
		{
			get
			{
				return this._schedule_id_PK;
			}
			set
			{
				if ((this._schedule_id_PK != value))
				{
					this.Onschedule_id_PKChanging(value);
					this.SendPropertyChanging();
					this._schedule_id_PK = value;
					this.SendPropertyChanged("schedule_id_PK");
					this.Onschedule_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_storedprocedure", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string schedule_storedprocedure
		{
			get
			{
				return this._schedule_storedprocedure;
			}
			set
			{
				if ((this._schedule_storedprocedure != value))
				{
					this.Onschedule_storedprocedureChanging(value);
					this.SendPropertyChanging();
					this._schedule_storedprocedure = value;
					this.SendPropertyChanged("schedule_storedprocedure");
					this.Onschedule_storedprocedureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_reportname", DbType="VarChar(50)")]
		public string schedule_reportname
		{
			get
			{
				return this._schedule_reportname;
			}
			set
			{
				if ((this._schedule_reportname != value))
				{
					this.Onschedule_reportnameChanging(value);
					this.SendPropertyChanging();
					this._schedule_reportname = value;
					this.SendPropertyChanged("schedule_reportname");
					this.Onschedule_reportnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_schedulename", DbType="VarChar(50)")]
		public string schedule_schedulename
		{
			get
			{
				return this._schedule_schedulename;
			}
			set
			{
				if ((this._schedule_schedulename != value))
				{
					this.Onschedule_schedulenameChanging(value);
					this.SendPropertyChanging();
					this._schedule_schedulename = value;
					this.SendPropertyChanged("schedule_schedulename");
					this.Onschedule_schedulenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_reporttype", DbType="VarChar(8)")]
		public string schedule_reporttype
		{
			get
			{
				return this._schedule_reporttype;
			}
			set
			{
				if ((this._schedule_reporttype != value))
				{
					this.Onschedule_reporttypeChanging(value);
					this.SendPropertyChanging();
					this._schedule_reporttype = value;
					this.SendPropertyChanged("schedule_reporttype");
					this.Onschedule_reporttypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_createddate", DbType="DateTime NOT NULL")]
		public System.DateTime schedule_createddate
		{
			get
			{
				return this._schedule_createddate;
			}
			set
			{
				if ((this._schedule_createddate != value))
				{
					this.Onschedule_createddateChanging(value);
					this.SendPropertyChanging();
					this._schedule_createddate = value;
					this.SendPropertyChanged("schedule_createddate");
					this.Onschedule_createddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_filters", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string schedule_filters
		{
			get
			{
				return this._schedule_filters;
			}
			set
			{
				if ((this._schedule_filters != value))
				{
					this.Onschedule_filtersChanging(value);
					this.SendPropertyChanging();
					this._schedule_filters = value;
					this.SendPropertyChanged("schedule_filters");
					this.Onschedule_filtersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_chosendropdown", DbType="VarChar(6)")]
		public string schedule_chosendropdown
		{
			get
			{
				return this._schedule_chosendropdown;
			}
			set
			{
				if ((this._schedule_chosendropdown != value))
				{
					this.Onschedule_chosendropdownChanging(value);
					this.SendPropertyChanging();
					this._schedule_chosendropdown = value;
					this.SendPropertyChanged("schedule_chosendropdown");
					this.Onschedule_chosendropdownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_chosenNodeIds", DbType="VarChar(MAX)")]
		public string schedule_chosenNodeIds
		{
			get
			{
				return this._schedule_chosenNodeIds;
			}
			set
			{
				if ((this._schedule_chosenNodeIds != value))
				{
					this.Onschedule_chosenNodeIdsChanging(value);
					this.SendPropertyChanging();
					this._schedule_chosenNodeIds = value;
					this.SendPropertyChanged("schedule_chosenNodeIds");
					this.Onschedule_chosenNodeIdsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_frequency", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string schedule_frequency
		{
			get
			{
				return this._schedule_frequency;
			}
			set
			{
				if ((this._schedule_frequency != value))
				{
					this.Onschedule_frequencyChanging(value);
					this.SendPropertyChanging();
					this._schedule_frequency = value;
					this.SendPropertyChanged("schedule_frequency");
					this.Onschedule_frequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_reportformat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string schedule_reportformat
		{
			get
			{
				return this._schedule_reportformat;
			}
			set
			{
				if ((this._schedule_reportformat != value))
				{
					this.Onschedule_reportformatChanging(value);
					this.SendPropertyChanging();
					this._schedule_reportformat = value;
					this.SendPropertyChanged("schedule_reportformat");
					this.Onschedule_reportformatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_emailaddresses", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string schedule_emailaddresses
		{
			get
			{
				return this._schedule_emailaddresses;
			}
			set
			{
				if ((this._schedule_emailaddresses != value))
				{
					this.Onschedule_emailaddressesChanging(value);
					this.SendPropertyChanging();
					this._schedule_emailaddresses = value;
					this.SendPropertyChanged("schedule_emailaddresses");
					this.Onschedule_emailaddressesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_user_id_FK", DbType="Int")]
		public System.Nullable<int> schedule_user_id_FK
		{
			get
			{
				return this._schedule_user_id_FK;
			}
			set
			{
				if ((this._schedule_user_id_FK != value))
				{
					this.Onschedule_user_id_FKChanging(value);
					this.SendPropertyChanging();
					this._schedule_user_id_FK = value;
					this.SendPropertyChanged("schedule_user_id_FK");
					this.Onschedule_user_id_FKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_Active", DbType="Bit")]
		public System.Nullable<bool> schedule_Active
		{
			get
			{
				return this._schedule_Active;
			}
			set
			{
				if ((this._schedule_Active != value))
				{
					this.Onschedule_ActiveChanging(value);
					this.SendPropertyChanging();
					this._schedule_Active = value;
					this.SendPropertyChanged("schedule_Active");
					this.Onschedule_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protfolio_ID", DbType="Int")]
		public System.Nullable<int> Protfolio_ID
		{
			get
			{
				return this._Protfolio_ID;
			}
			set
			{
				if ((this._Protfolio_ID != value))
				{
					this.OnProtfolio_IDChanging(value);
					this.SendPropertyChanging();
					this._Protfolio_ID = value;
					this.SendPropertyChanged("Protfolio_ID");
					this.OnProtfolio_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_Time", DbType="Int")]
		public System.Nullable<int> schedule_Time
		{
			get
			{
				return this._schedule_Time;
			}
			set
			{
				if ((this._schedule_Time != value))
				{
					this.Onschedule_TimeChanging(value);
					this.SendPropertyChanging();
					this._schedule_Time = value;
					this.SendPropertyChanged("schedule_Time");
					this.Onschedule_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule_Graph", DbType="VarChar(15)")]
		public string schedule_Graph
		{
			get
			{
				return this._schedule_Graph;
			}
			set
			{
				if ((this._schedule_Graph != value))
				{
					this.Onschedule_GraphChanging(value);
					this.SendPropertyChanging();
					this._schedule_Graph = value;
					this.SendPropertyChanged("schedule_Graph");
					this.Onschedule_GraphChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ReportTotals")]
	public partial class tbl_ReportTotal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Report_Id;
		
		private string _Report_Name;
		
		private string _Report_Type;
		
		private string _Report_Totals;
		
		private string _Report_Performance;
		
		private string _Report_SubTotals;
		
		private string _Report_TableJoins;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReport_IdChanging(int value);
    partial void OnReport_IdChanged();
    partial void OnReport_NameChanging(string value);
    partial void OnReport_NameChanged();
    partial void OnReport_TypeChanging(string value);
    partial void OnReport_TypeChanged();
    partial void OnReport_TotalsChanging(string value);
    partial void OnReport_TotalsChanged();
    partial void OnReport_PerformanceChanging(string value);
    partial void OnReport_PerformanceChanged();
    partial void OnReport_SubTotalsChanging(string value);
    partial void OnReport_SubTotalsChanged();
    partial void OnReport_TableJoinsChanging(string value);
    partial void OnReport_TableJoinsChanged();
    #endregion
		
		public tbl_ReportTotal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Report_Id
		{
			get
			{
				return this._Report_Id;
			}
			set
			{
				if ((this._Report_Id != value))
				{
					this.OnReport_IdChanging(value);
					this.SendPropertyChanging();
					this._Report_Id = value;
					this.SendPropertyChanged("Report_Id");
					this.OnReport_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Report_Name
		{
			get
			{
				return this._Report_Name;
			}
			set
			{
				if ((this._Report_Name != value))
				{
					this.OnReport_NameChanging(value);
					this.SendPropertyChanging();
					this._Report_Name = value;
					this.SendPropertyChanged("Report_Name");
					this.OnReport_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Type", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Report_Type
		{
			get
			{
				return this._Report_Type;
			}
			set
			{
				if ((this._Report_Type != value))
				{
					this.OnReport_TypeChanging(value);
					this.SendPropertyChanging();
					this._Report_Type = value;
					this.SendPropertyChanged("Report_Type");
					this.OnReport_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Totals", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Report_Totals
		{
			get
			{
				return this._Report_Totals;
			}
			set
			{
				if ((this._Report_Totals != value))
				{
					this.OnReport_TotalsChanging(value);
					this.SendPropertyChanging();
					this._Report_Totals = value;
					this.SendPropertyChanged("Report_Totals");
					this.OnReport_TotalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Performance", DbType="VarChar(200)")]
		public string Report_Performance
		{
			get
			{
				return this._Report_Performance;
			}
			set
			{
				if ((this._Report_Performance != value))
				{
					this.OnReport_PerformanceChanging(value);
					this.SendPropertyChanging();
					this._Report_Performance = value;
					this.SendPropertyChanged("Report_Performance");
					this.OnReport_PerformanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_SubTotals", DbType="VarChar(200)")]
		public string Report_SubTotals
		{
			get
			{
				return this._Report_SubTotals;
			}
			set
			{
				if ((this._Report_SubTotals != value))
				{
					this.OnReport_SubTotalsChanging(value);
					this.SendPropertyChanging();
					this._Report_SubTotals = value;
					this.SendPropertyChanged("Report_SubTotals");
					this.OnReport_SubTotalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_TableJoins", DbType="VarChar(100)")]
		public string Report_TableJoins
		{
			get
			{
				return this._Report_TableJoins;
			}
			set
			{
				if ((this._Report_TableJoins != value))
				{
					this.OnReport_TableJoinsChanging(value);
					this.SendPropertyChanging();
					this._Report_TableJoins = value;
					this.SendPropertyChanged("Report_TableJoins");
					this.OnReport_TableJoinsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KPI")]
	public partial class tbl_KPI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KPI_ID;
		
		private System.Nullable<int> _site_id_PK;
		
		private System.Nullable<int> _KPI_Answered_Rate_Day;
		
		private System.Nullable<int> _KPI_Abandoned_Rate_Day;
		
		private System.Nullable<int> _KPI_Response_Rate_Day;
		
		private System.Nullable<int> _KPI_Answered_Rate_Eve;
		
		private System.Nullable<int> _KPI_Abandoned_Rate_Eve;
		
		private System.Nullable<int> _KPI_Response_Rate_Eve;
		
		private System.Nullable<int> _KPI_Answered_Rate_WeekEnd;
		
		private System.Nullable<int> _KPI_Abandoned_Rate_WeekEnd;
		
		private System.Nullable<int> _KPI_Response_Rate_Weekend;
		
		private System.Nullable<double> _KPI_Total_Spend_Month;
		
		private System.Nullable<int> _KPI_Spend_International;
		
		private System.Nullable<int> _KPI_Spend_Premiumrate;
		
		private System.Nullable<int> _KPI_Spend_LocalRate;
		
		private System.Nullable<int> _KPI_Spend_National;
		
		private System.Nullable<int> _KPI_Spend_Local;
		
		private System.Nullable<int> _KPI_Spend_Mobiles;
		
		private System.Nullable<int> _KPI_Spend_Pagers;
		
		private System.Nullable<int> _KPI_DQ;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKPI_IDChanging(int value);
    partial void OnKPI_IDChanged();
    partial void Onsite_id_PKChanging(System.Nullable<int> value);
    partial void Onsite_id_PKChanged();
    partial void OnKPI_Answered_Rate_DayChanging(System.Nullable<int> value);
    partial void OnKPI_Answered_Rate_DayChanged();
    partial void OnKPI_Abandoned_Rate_DayChanging(System.Nullable<int> value);
    partial void OnKPI_Abandoned_Rate_DayChanged();
    partial void OnKPI_Response_Rate_DayChanging(System.Nullable<int> value);
    partial void OnKPI_Response_Rate_DayChanged();
    partial void OnKPI_Answered_Rate_EveChanging(System.Nullable<int> value);
    partial void OnKPI_Answered_Rate_EveChanged();
    partial void OnKPI_Abandoned_Rate_EveChanging(System.Nullable<int> value);
    partial void OnKPI_Abandoned_Rate_EveChanged();
    partial void OnKPI_Response_Rate_EveChanging(System.Nullable<int> value);
    partial void OnKPI_Response_Rate_EveChanged();
    partial void OnKPI_Answered_Rate_WeekEndChanging(System.Nullable<int> value);
    partial void OnKPI_Answered_Rate_WeekEndChanged();
    partial void OnKPI_Abandoned_Rate_WeekEndChanging(System.Nullable<int> value);
    partial void OnKPI_Abandoned_Rate_WeekEndChanged();
    partial void OnKPI_Response_Rate_WeekendChanging(System.Nullable<int> value);
    partial void OnKPI_Response_Rate_WeekendChanged();
    partial void OnKPI_Total_Spend_MonthChanging(System.Nullable<double> value);
    partial void OnKPI_Total_Spend_MonthChanged();
    partial void OnKPI_Spend_InternationalChanging(System.Nullable<int> value);
    partial void OnKPI_Spend_InternationalChanged();
    partial void OnKPI_Spend_PremiumrateChanging(System.Nullable<int> value);
    partial void OnKPI_Spend_PremiumrateChanged();
    partial void OnKPI_Spend_LocalRateChanging(System.Nullable<int> value);
    partial void OnKPI_Spend_LocalRateChanged();
    partial void OnKPI_Spend_NationalChanging(System.Nullable<int> value);
    partial void OnKPI_Spend_NationalChanged();
    partial void OnKPI_Spend_LocalChanging(System.Nullable<int> value);
    partial void OnKPI_Spend_LocalChanged();
    partial void OnKPI_Spend_MobilesChanging(System.Nullable<int> value);
    partial void OnKPI_Spend_MobilesChanged();
    partial void OnKPI_Spend_PagersChanging(System.Nullable<int> value);
    partial void OnKPI_Spend_PagersChanged();
    partial void OnKPI_DQChanging(System.Nullable<int> value);
    partial void OnKPI_DQChanged();
    #endregion
		
		public tbl_KPI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KPI_ID
		{
			get
			{
				return this._KPI_ID;
			}
			set
			{
				if ((this._KPI_ID != value))
				{
					this.OnKPI_IDChanging(value);
					this.SendPropertyChanging();
					this._KPI_ID = value;
					this.SendPropertyChanged("KPI_ID");
					this.OnKPI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_id_PK", DbType="Int")]
		public System.Nullable<int> site_id_PK
		{
			get
			{
				return this._site_id_PK;
			}
			set
			{
				if ((this._site_id_PK != value))
				{
					this.Onsite_id_PKChanging(value);
					this.SendPropertyChanging();
					this._site_id_PK = value;
					this.SendPropertyChanged("site_id_PK");
					this.Onsite_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Answered_Rate_Day", DbType="Int")]
		public System.Nullable<int> KPI_Answered_Rate_Day
		{
			get
			{
				return this._KPI_Answered_Rate_Day;
			}
			set
			{
				if ((this._KPI_Answered_Rate_Day != value))
				{
					this.OnKPI_Answered_Rate_DayChanging(value);
					this.SendPropertyChanging();
					this._KPI_Answered_Rate_Day = value;
					this.SendPropertyChanged("KPI_Answered_Rate_Day");
					this.OnKPI_Answered_Rate_DayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Abandoned_Rate_Day", DbType="Int")]
		public System.Nullable<int> KPI_Abandoned_Rate_Day
		{
			get
			{
				return this._KPI_Abandoned_Rate_Day;
			}
			set
			{
				if ((this._KPI_Abandoned_Rate_Day != value))
				{
					this.OnKPI_Abandoned_Rate_DayChanging(value);
					this.SendPropertyChanging();
					this._KPI_Abandoned_Rate_Day = value;
					this.SendPropertyChanged("KPI_Abandoned_Rate_Day");
					this.OnKPI_Abandoned_Rate_DayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Response_Rate_Day", DbType="Int")]
		public System.Nullable<int> KPI_Response_Rate_Day
		{
			get
			{
				return this._KPI_Response_Rate_Day;
			}
			set
			{
				if ((this._KPI_Response_Rate_Day != value))
				{
					this.OnKPI_Response_Rate_DayChanging(value);
					this.SendPropertyChanging();
					this._KPI_Response_Rate_Day = value;
					this.SendPropertyChanged("KPI_Response_Rate_Day");
					this.OnKPI_Response_Rate_DayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Answered_Rate_Eve", DbType="Int")]
		public System.Nullable<int> KPI_Answered_Rate_Eve
		{
			get
			{
				return this._KPI_Answered_Rate_Eve;
			}
			set
			{
				if ((this._KPI_Answered_Rate_Eve != value))
				{
					this.OnKPI_Answered_Rate_EveChanging(value);
					this.SendPropertyChanging();
					this._KPI_Answered_Rate_Eve = value;
					this.SendPropertyChanged("KPI_Answered_Rate_Eve");
					this.OnKPI_Answered_Rate_EveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Abandoned_Rate_Eve", DbType="Int")]
		public System.Nullable<int> KPI_Abandoned_Rate_Eve
		{
			get
			{
				return this._KPI_Abandoned_Rate_Eve;
			}
			set
			{
				if ((this._KPI_Abandoned_Rate_Eve != value))
				{
					this.OnKPI_Abandoned_Rate_EveChanging(value);
					this.SendPropertyChanging();
					this._KPI_Abandoned_Rate_Eve = value;
					this.SendPropertyChanged("KPI_Abandoned_Rate_Eve");
					this.OnKPI_Abandoned_Rate_EveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Response_Rate_Eve", DbType="Int")]
		public System.Nullable<int> KPI_Response_Rate_Eve
		{
			get
			{
				return this._KPI_Response_Rate_Eve;
			}
			set
			{
				if ((this._KPI_Response_Rate_Eve != value))
				{
					this.OnKPI_Response_Rate_EveChanging(value);
					this.SendPropertyChanging();
					this._KPI_Response_Rate_Eve = value;
					this.SendPropertyChanged("KPI_Response_Rate_Eve");
					this.OnKPI_Response_Rate_EveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Answered_Rate_WeekEnd", DbType="Int")]
		public System.Nullable<int> KPI_Answered_Rate_WeekEnd
		{
			get
			{
				return this._KPI_Answered_Rate_WeekEnd;
			}
			set
			{
				if ((this._KPI_Answered_Rate_WeekEnd != value))
				{
					this.OnKPI_Answered_Rate_WeekEndChanging(value);
					this.SendPropertyChanging();
					this._KPI_Answered_Rate_WeekEnd = value;
					this.SendPropertyChanged("KPI_Answered_Rate_WeekEnd");
					this.OnKPI_Answered_Rate_WeekEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Abandoned_Rate_WeekEnd", DbType="Int")]
		public System.Nullable<int> KPI_Abandoned_Rate_WeekEnd
		{
			get
			{
				return this._KPI_Abandoned_Rate_WeekEnd;
			}
			set
			{
				if ((this._KPI_Abandoned_Rate_WeekEnd != value))
				{
					this.OnKPI_Abandoned_Rate_WeekEndChanging(value);
					this.SendPropertyChanging();
					this._KPI_Abandoned_Rate_WeekEnd = value;
					this.SendPropertyChanged("KPI_Abandoned_Rate_WeekEnd");
					this.OnKPI_Abandoned_Rate_WeekEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Response_Rate_Weekend", DbType="Int")]
		public System.Nullable<int> KPI_Response_Rate_Weekend
		{
			get
			{
				return this._KPI_Response_Rate_Weekend;
			}
			set
			{
				if ((this._KPI_Response_Rate_Weekend != value))
				{
					this.OnKPI_Response_Rate_WeekendChanging(value);
					this.SendPropertyChanging();
					this._KPI_Response_Rate_Weekend = value;
					this.SendPropertyChanged("KPI_Response_Rate_Weekend");
					this.OnKPI_Response_Rate_WeekendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Total_Spend_Month", DbType="Float")]
		public System.Nullable<double> KPI_Total_Spend_Month
		{
			get
			{
				return this._KPI_Total_Spend_Month;
			}
			set
			{
				if ((this._KPI_Total_Spend_Month != value))
				{
					this.OnKPI_Total_Spend_MonthChanging(value);
					this.SendPropertyChanging();
					this._KPI_Total_Spend_Month = value;
					this.SendPropertyChanged("KPI_Total_Spend_Month");
					this.OnKPI_Total_Spend_MonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Spend_International", DbType="Int")]
		public System.Nullable<int> KPI_Spend_International
		{
			get
			{
				return this._KPI_Spend_International;
			}
			set
			{
				if ((this._KPI_Spend_International != value))
				{
					this.OnKPI_Spend_InternationalChanging(value);
					this.SendPropertyChanging();
					this._KPI_Spend_International = value;
					this.SendPropertyChanged("KPI_Spend_International");
					this.OnKPI_Spend_InternationalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Spend_Premiumrate", DbType="Int")]
		public System.Nullable<int> KPI_Spend_Premiumrate
		{
			get
			{
				return this._KPI_Spend_Premiumrate;
			}
			set
			{
				if ((this._KPI_Spend_Premiumrate != value))
				{
					this.OnKPI_Spend_PremiumrateChanging(value);
					this.SendPropertyChanging();
					this._KPI_Spend_Premiumrate = value;
					this.SendPropertyChanged("KPI_Spend_Premiumrate");
					this.OnKPI_Spend_PremiumrateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Spend_LocalRate", DbType="Int")]
		public System.Nullable<int> KPI_Spend_LocalRate
		{
			get
			{
				return this._KPI_Spend_LocalRate;
			}
			set
			{
				if ((this._KPI_Spend_LocalRate != value))
				{
					this.OnKPI_Spend_LocalRateChanging(value);
					this.SendPropertyChanging();
					this._KPI_Spend_LocalRate = value;
					this.SendPropertyChanged("KPI_Spend_LocalRate");
					this.OnKPI_Spend_LocalRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Spend_National", DbType="Int")]
		public System.Nullable<int> KPI_Spend_National
		{
			get
			{
				return this._KPI_Spend_National;
			}
			set
			{
				if ((this._KPI_Spend_National != value))
				{
					this.OnKPI_Spend_NationalChanging(value);
					this.SendPropertyChanging();
					this._KPI_Spend_National = value;
					this.SendPropertyChanged("KPI_Spend_National");
					this.OnKPI_Spend_NationalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Spend_Local", DbType="Int")]
		public System.Nullable<int> KPI_Spend_Local
		{
			get
			{
				return this._KPI_Spend_Local;
			}
			set
			{
				if ((this._KPI_Spend_Local != value))
				{
					this.OnKPI_Spend_LocalChanging(value);
					this.SendPropertyChanging();
					this._KPI_Spend_Local = value;
					this.SendPropertyChanged("KPI_Spend_Local");
					this.OnKPI_Spend_LocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Spend_Mobiles", DbType="Int")]
		public System.Nullable<int> KPI_Spend_Mobiles
		{
			get
			{
				return this._KPI_Spend_Mobiles;
			}
			set
			{
				if ((this._KPI_Spend_Mobiles != value))
				{
					this.OnKPI_Spend_MobilesChanging(value);
					this.SendPropertyChanging();
					this._KPI_Spend_Mobiles = value;
					this.SendPropertyChanged("KPI_Spend_Mobiles");
					this.OnKPI_Spend_MobilesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_Spend_Pagers", DbType="Int")]
		public System.Nullable<int> KPI_Spend_Pagers
		{
			get
			{
				return this._KPI_Spend_Pagers;
			}
			set
			{
				if ((this._KPI_Spend_Pagers != value))
				{
					this.OnKPI_Spend_PagersChanging(value);
					this.SendPropertyChanging();
					this._KPI_Spend_Pagers = value;
					this.SendPropertyChanged("KPI_Spend_Pagers");
					this.OnKPI_Spend_PagersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_DQ", DbType="Int")]
		public System.Nullable<int> KPI_DQ
		{
			get
			{
				return this._KPI_DQ;
			}
			set
			{
				if ((this._KPI_DQ != value))
				{
					this.OnKPI_DQChanging(value);
					this.SendPropertyChanging();
					this._KPI_DQ = value;
					this.SendPropertyChanged("KPI_DQ");
					this.OnKPI_DQChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usersite")]
	public partial class tbl_usersite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usersite_id_PK;
		
		private int _usersite_user_id_FK;
		
		private int _usersite_site_id_FK;
		
		private System.Nullable<bool> _user_active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusersite_id_PKChanging(int value);
    partial void Onusersite_id_PKChanged();
    partial void Onusersite_user_id_FKChanging(int value);
    partial void Onusersite_user_id_FKChanged();
    partial void Onusersite_site_id_FKChanging(int value);
    partial void Onusersite_site_id_FKChanged();
    partial void Onuser_activeChanging(System.Nullable<bool> value);
    partial void Onuser_activeChanged();
    #endregion
		
		public tbl_usersite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usersite_id_PK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usersite_id_PK
		{
			get
			{
				return this._usersite_id_PK;
			}
			set
			{
				if ((this._usersite_id_PK != value))
				{
					this.Onusersite_id_PKChanging(value);
					this.SendPropertyChanging();
					this._usersite_id_PK = value;
					this.SendPropertyChanged("usersite_id_PK");
					this.Onusersite_id_PKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usersite_user_id_FK", DbType="Int NOT NULL")]
		public int usersite_user_id_FK
		{
			get
			{
				return this._usersite_user_id_FK;
			}
			set
			{
				if ((this._usersite_user_id_FK != value))
				{
					this.Onusersite_user_id_FKChanging(value);
					this.SendPropertyChanging();
					this._usersite_user_id_FK = value;
					this.SendPropertyChanged("usersite_user_id_FK");
					this.Onusersite_user_id_FKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usersite_site_id_FK", DbType="Int NOT NULL")]
		public int usersite_site_id_FK
		{
			get
			{
				return this._usersite_site_id_FK;
			}
			set
			{
				if ((this._usersite_site_id_FK != value))
				{
					this.Onusersite_site_id_FKChanging(value);
					this.SendPropertyChanging();
					this._usersite_site_id_FK = value;
					this.SendPropertyChanged("usersite_site_id_FK");
					this.Onusersite_site_id_FKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_active", DbType="Bit")]
		public System.Nullable<bool> user_active
		{
			get
			{
				return this._user_active;
			}
			set
			{
				if ((this._user_active != value))
				{
					this.Onuser_activeChanging(value);
					this.SendPropertyChanging();
					this._user_active = value;
					this.SendPropertyChanged("user_active");
					this.Onuser_activeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
